# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Daypub < Formula
  desc "A tool for publishing day entries as markdown or Hugo content"
  homepage "https://github.com/samf/homebrew-samf"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samf/daypub/releases/download/v0.3.1/daypub_Darwin_x86_64.tar.gz"
      sha256 "726e549fc0b8902e85525737c3db43314248f650b91b6b646ed933c11dddd450"

      define_method(:install) do
        bin.install "daypub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samf/daypub/releases/download/v0.3.1/daypub_Darwin_arm64.tar.gz"
      sha256 "8e04fee92734fcfb7f366243b8eb1190eeeee7b85e985b3ff31fd172bf47e43c"

      define_method(:install) do
        bin.install "daypub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samf/daypub/releases/download/v0.3.1/daypub_Linux_x86_64.tar.gz"
      sha256 "101a37a49e1a45795b64057eedb7eee36bee7fe4a3a4525e490a0c05d82131c6"
      define_method(:install) do
        bin.install "daypub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samf/daypub/releases/download/v0.3.1/daypub_Linux_arm64.tar.gz"
      sha256 "a38bee9cd0660d1f2857d6f06f9f4bb3b2382fb1191cdad933cf89038dfa3d31"
      define_method(:install) do
        bin.install "daypub"
      end
    end
  end

  test do
    system "#{bin}/daypub", "--help"
  end
end
