# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Daypub < Formula
  desc "A tool for publishing day entries as markdown or Hugo content"
  homepage "https://github.com/samf/daypub"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samf/daypub/releases/download/v0.1.6/daypub_Darwin_x86_64.tar.gz"
      sha256 "c5613e23e80e73ea22cb9819d68803e93f7dbd5f25060c1af5952b11791f339b"

      def install
        bin.install "daypub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samf/daypub/releases/download/v0.1.6/daypub_Darwin_arm64.tar.gz"
      sha256 "9268c93707a0b99018839b77419e2bd4c84507258f6188c9bce0ef466ebe9fe2"

      def install
        bin.install "daypub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samf/daypub/releases/download/v0.1.6/daypub_Linux_x86_64.tar.gz"
      sha256 "9c71dceaa22c80f534009c1cc5173060a4356f22e68e73cd3a1fa4339b2f5761"
      def install
        bin.install "daypub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samf/daypub/releases/download/v0.1.6/daypub_Linux_arm64.tar.gz"
      sha256 "05b8ba1ef0ce11876f9342bc17aaa309383e3d2afd984044799c2fc560f41231"
      def install
        bin.install "daypub"
      end
    end
  end

  test do
    system "#{bin}/daypub", "--help"
  end
end
