# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snake < Formula
  desc "CLI for The Snake Can temporary file storage"
  homepage "https://github.com/samf/snake"
  version "0.11.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samf/snake/releases/download/v0.11.1/snake_darwin_amd64.tar.gz"
      sha256 "51ecff24bdbfeaaee92b6e0255ebadf8ede1b92a91cceab05b354dddb1726bf6"

      define_method(:install) do
        bin.install "snake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samf/snake/releases/download/v0.11.1/snake_darwin_arm64.tar.gz"
      sha256 "d61f286fd27adf5f71c9ccf9e4c98066cc7653b8ee41cedc04130d19a027be4a"

      define_method(:install) do
        bin.install "snake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samf/snake/releases/download/v0.11.1/snake_linux_amd64.tar.gz"
      sha256 "d132c7fe32d08ffd42b43728174318b2bb9eb10cad8e2307f60a8eafb1ff49ab"
      define_method(:install) do
        bin.install "snake"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samf/snake/releases/download/v0.11.1/snake_linux_arm64.tar.gz"
      sha256 "ec8d972d04a0476e9aad39a1123107f2b9d01e967a3e10cf4ddea24689076a1e"
      define_method(:install) do
        bin.install "snake"
      end
    end
  end

  test do
    system "#{bin}/snake", "--help"
  end
end
