# typed: false
# frozen_string_literal: true

# This file is generated by the astrobin-csv release workflow. DO NOT EDIT.
class AstrobinCsv < Formula
  desc "Generate an AstroBin acquisition CSV from NINA FITS/XISF light frames"
  homepage "https://github.com/samf/astrobin-csv"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/samf/astrobin-csv/releases/download/v0.1.0/astrobin-csv_0.1.0_darwin_amd64.tar.gz"
      sha256 "32867f4593e104c63e6c65dec981cff5a434449fbbe4c2e55c4609285488a3fe"
    end
    on_arm do
      url "https://github.com/samf/astrobin-csv/releases/download/v0.1.0/astrobin-csv_0.1.0_darwin_arm64.tar.gz"
      sha256 "0cf94e984cd5fa61e0130f85eaaf34e605d06f9123eb460cf939f746d39eab38"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/samf/astrobin-csv/releases/download/v0.1.0/astrobin-csv_0.1.0_linux_amd64.tar.gz"
      sha256 "5ca533b485835bfc782fc2d5531199d3be934902529a6d4d22816b6f49f79c21"
    end
    on_arm do
      url "https://github.com/samf/astrobin-csv/releases/download/v0.1.0/astrobin-csv_0.1.0_linux_arm64.tar.gz"
      sha256 "35c89661e295af0c67c60c30b997d73ee63556b2570e6218ebd4be552939ec1f"
    end
  end

  def install
    bin.install "astrobin-csv"
  end

  test do
    system "#{bin}/astrobin-csv", "--help"
  end
end
