# typed: false
# frozen_string_literal: true

# This file is generated by the astrobin-csv release workflow. DO NOT EDIT.
class AstrobinCsv < Formula
  desc "Generate an AstroBin acquisition CSV from NINA FITS/XISF light frames"
  homepage "https://github.com/samf/astrobin-csv"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/samf/astrobin-csv/releases/download/v0.3.0/astrobin-csv_0.3.0_darwin_amd64.tar.gz"
      sha256 "22b8afddd5ce383d99f990ef34c24e390d644fc80c24b7019cad4e30b5d57aef"
    end
    on_arm do
      url "https://github.com/samf/astrobin-csv/releases/download/v0.3.0/astrobin-csv_0.3.0_darwin_arm64.tar.gz"
      sha256 "60eca4483fa979650787c5ba87ada875ad5f3771a964f356f1dc74c4dc2b8ffa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/samf/astrobin-csv/releases/download/v0.3.0/astrobin-csv_0.3.0_linux_amd64.tar.gz"
      sha256 "4d7ca969ee58a1f6bfd036ed0bc036cd68c536e8e0e2203f3d787295ca2a0393"
    end
    on_arm do
      url "https://github.com/samf/astrobin-csv/releases/download/v0.3.0/astrobin-csv_0.3.0_linux_arm64.tar.gz"
      sha256 "0ee575ef3a6ad15ca26a1c16337049242fcf6ad0ebe119bd4ec947d488ae6b82"
    end
  end

  def install
    bin.install "astrobin-csv"
  end

  test do
    system "#{bin}/astrobin-csv", "--help"
  end
end
