# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snake < Formula
  desc "CLI for The Snake Can temporary file storage"
  homepage "https://github.com/samf/snake"
  version "0.12.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samf/snake/releases/download/v0.12.0/snake_darwin_amd64.tar.gz"
      sha256 "5c4d5f5682e3424acdec0ad44fc09cbbd4e05b17e7a3e9d5e9097a77cb5ecd71"

      define_method(:install) do
        bin.install "snake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samf/snake/releases/download/v0.12.0/snake_darwin_arm64.tar.gz"
      sha256 "287605f632fd98dd495562de7da6e4b2aeb0eb2e1ce469a2ee361d459ce082c8"

      define_method(:install) do
        bin.install "snake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samf/snake/releases/download/v0.12.0/snake_linux_amd64.tar.gz"
      sha256 "018e3881d077ff97816f1258a3274ed5373b2ba9b9104e4fed9bd57f9615fab4"
      define_method(:install) do
        bin.install "snake"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samf/snake/releases/download/v0.12.0/snake_linux_arm64.tar.gz"
      sha256 "f7dec3a909bd8b33165093f2342902828a7c1e18486a2249de910f90a2b9391b"
      define_method(:install) do
        bin.install "snake"
      end
    end
  end

  test do
    system "#{bin}/snake", "--help"
  end
end
